### ISSUE TITLE
research: Analyse Priority of Widgets from existing Müsli 

### ISSUE THREAD

**Issue by Janik7777** [pvs-hd-tea/MuesliNext#1]
Count how often each Widget is used in the different pages of Müsli. Create a Matrix containing the information and group the Widgets according to their priority

**Comment by cyamn** [comment]
Result (in order of importance)
- Basic elements 66%
  - text, button, links, textinput, checkbox, switch
  - needed everywhere
  - straightforward: design and implementation should be easy
- Database related elements 32%
  - dynamic vals, derived vals, list selection, tables
  - difficult design
  - difficult implementation (partly done by previous project)
- Nice to have 2%
  - tooltips, rich text, file picker
  - nice to have = not important

More detailed result available in:
- our presentations
- [goole table (ask me for access)](https://docs.google.com/spreadsheets/d/1jncBSuft15woPgMqHyhYC2OISkpAs4kqEJGwV9UpjRs/edit#gid=195327831)
