### ISSUE TITLE
feat: implement tables widget

### ISSUE THREAD

**Issue by Janik7777** [pvs-hd-tea/MuesliNext#10]
Right now tables are already part of the project. Make it possible for them to be part of our pages as widgets

**Comment by denitsa-ilieva** [comment]
Until now: Table.ts is implemented in data/defenitions.
Next step: connect Table.ts with Block.ts

**Comment by cyamn** [comment]
Table data from the backend has the following form by default:

```js

 {
  "table": {
    "id": 4,
    "name": "${table-name}",
    "key": "p${projectnumber}_${table-name}"
  },
  "columns": [
    {
      "id": 12, // this column is the id: the key for every column
      "name": "_id",
      "type": "increments",
      "attributes": {}
    },
    {
      "id": 13, // don't know what this is used for
      "name": "${column-name}",
      "type": "${column-type}",
      "attributes": {}
    },
    ...
  ],
  "rows": [
    {
      "_id": 1,
      "${column-name}": "some value",
    },
    ...
  ]
}
```

for example the table with the name "example":
|_id|number|string|boolean|
|---|---|---|---|
|1|1|foo|TRUE|
|2|42|bar|FALSE|

will return this object when fetched

```js

 {
  "table": {
    "id": 4,
    "name": "example",
    "key": "p1_example"
  },
  "columns": [
    {
      "id": 12,
      "name": "_id",
      "type": "increments",
      "attributes": {}
    },
    {
      "id": 13,
      "name": "number",
      "type": "integer",
      "attributes": {}
    },
    {
      "id": 14,
      "name": "string",
      "type": "string",
      "attributes": {}
    },
    {
      "id": 15,
      "name": "boolean",
      "type": "boolean",
      "attributes": {}
    }
  ],
  // This is the more interesting part maybe
  // maybe this should to be reshaped into a 2D array
  "rows": [
    {
      "_id": 1,
      "number": 1,
      "string": "foo",
      "boolean": true
    },
    {
      "_id": 2,
      "number": 42,
      "string": "bar",
      "boolean": false
    }
  ]
}
```

Maybe it is helpful to look at the [static table plugin](https://github.com/editor-js/table/blob/master/src/table.js) for inspiration or just modify it.

**Comment by denitsa-ilieva** [comment]
https://github.com/pvs-hd-tea/MuesliNext/tree/feat/dynamic-table

**Comment by Janik7777** [comment]
@denitsa-ilieva 
- We need better table layout: columns need space in between
- Don't understand the placeholder of the input field
- css for input field
- Don't show input field entry in the preview mode, only the table

**Comment by denitsa-ilieva** [comment]
@Janik7777 the layout will be improved soon. The placeholder of the input and the input field entry in the preview mode are changed.

**Comment by cyamn** [comment]
I added some css
