### ISSUE TITLE
feat: implement usage of derived values

### ISSUE THREAD

**Issue by Janik7777** [pvs-hd-tea/MuesliNext#13]
Implement the possibility to use derived values that are calculated from database entries

**Comment by denitsa-ilieva** [comment]
First, implement a widget with the following functionality for deriving the dynamic values: addition or calculation of the mean value for certain values from the table columns/rows

**Comment by denitsa-ilieva** [comment]
#91

**Comment by denitsa-ilieva** [comment]
The other functionalities will be implemented in other issues
