### ISSUE TITLE
feat: implement static list selection widget

### ISSUE THREAD

**Issue by Janik7777** [pvs-hd-tea/MuesliNext#19]
Implement a dropdown selector widget to enter one of many static possible values for a specific column of a table entry of our database. It should show the current status of the entry.

**Comment by cyamn** [comment]
until now we can update table entries with an input field. (Example update Example.integer.1 to "49"). Goal of this issue is to also be able to update it via predefined values by using a static dropdown selector

**Comment by denitsa-ilieva** [comment]
Function for the saving the changed values in the json-file has to be implemented
