### ISSUE TITLE
research: come up with a way to define the app that Web-Gen should produce

### ISSUE THREAD

**Issue by cyamn** [pvs-hd-tea/MuesliNext#26]
**How** can a user (a non coder) define any app tailored to his needs?

This could be done via:
a. extensible configfile & tables
b. command builder (similar to latex)
c. ui builder (WYSIWYG)

**Comment by Janik7777** [comment]
We decided to start by creating a webapp with react now. In this programm will be a typescript or a xml file that the enduser of the generator has to modify. There he can specify our predefined widgets and functions to be part of a page.

**Comment by denitsa-ilieva** [comment]
Possible initialization of the json file by the end-user for the creation of a static text page wit react:
[
{
    "nav_link": "/about",
    "page_name": "About",
    "content": "<h1> About more info </h1>"
    },
{...
}
]

**Comment by cyamn** [comment]
We decided to implement widgets as components in react. The Webapp-generator will create a React app with prepopulated widgets.
