### ISSUE TITLE
research: Try to implement parts of Müsli with coda.io

### ISSUE THREAD

**Issue by Janik7777** [pvs-hd-tea/MuesliNext#3]
Implement parts of Müsli (widgets and functionalities) with coda.io. Get inspiration for the implementation of the different widgets and functionalities

**Comment by denitsa-ilieva** [comment]
The relevant Widgets like static text, buttons, some dynamic values, links, text inputs, list selections (static and dynamic), tables can be implemeted well in coda.io.

**Comment by denitsa-ilieva** [comment]
Many pages and Widgets were implemented in coda.io.
