### ISSUE TITLE
research: Try to implement parts of Müsli with notion.so

### ISSUE THREAD

**Issue by Janik7777** [pvs-hd-tea/MuesliNext#4]
Implement parts of Müsli (widgets and functionalities) with notion.so. Get inspiration for the implementation of the different widgets and functionalities

**Comment by cyamn** [comment]
very user friendly interface but not really suitable to generate dynamic sites:

- missing widgets like button, input, sliders
- just markdown with (very nice) additional widgets
- thus probably not for our use-case
