### ISSUE TITLE
feat: setup intutable and database

### ISSUE THREAD

**Issue by cyamn** [pvs-hd-tea/MuesliNext#57]
The goal of this issue is to allow us to access and manipulate a database with [intutable](https://gitlab.com/intutable). It is probably good to run the database as a docker-container to make setup more convenient.

This will allow us to implement dynamic widgets in the long term

**Comment by Janik7777** [comment]
Adjusted the tests to work now. @cyamn pls find a solution for the linter problem so we can push this
