### ISSUE TITLE
bug: Inline dynamic Value rendering can result in endless loop

### ISSUE THREAD

**Issue by Janik7777** [pvs-hd-tea/MuesliNext#76]
currently we don't stop searching, till no "//dynamicValue:" is in our text anymore. But we only replace it if we also find a ":dynamicValue//" afterwards.

**Comment by cyamn** [comment]
suggestion: try fixing by using regex.
E.g. something like:
`\/\/dynamicValue:{"tableName":"[a-zA-Z]+","columnName":"[a-zA-Z]+","entryKey":"[a-zA-Z]+"}:dynamicValue\/\/` 

Also I suggest a(n additional) simpler syntax like `$table.column.key` with regex: `\$[a-zA-Z]+\.[a-zA-Z]+\.[a-zA-Z]+` as it's faster to write (but not as intuitive)

**Comment by Janik7777** [comment]
move for now, because it most likely will be obsolete after we change how to address dynamic Values

**Comment by Janik7777** [comment]
solved during #73
