### ISSUE TITLE
feat: form field widget

### ISSUE THREAD

**Issue by cyamn** [pvs-hd-tea/MuesliNext#77]
With form field I mean a list of input fields.
The user should define the table name only and the widget should automatically generate one input field per table column.
Then the user can connect a submit type button to the form.

We will use input fields manly (only?) to insert/update into a database so I think this is convenient for the user and us.

Additionally one could give the user the ability to prefill some input fields (also with dynamic values if we feel confident)

**Comment by Janik7777** [comment]
In this context we also need a widget for entry overview of one table entry, that will show all fields of the table for this entry #83

**Comment by cyamn** [comment]
closed by #94
